# ruff: noqa: B018  # bare-name references are intentional in a vulture whitelist
#
# Audited per #295 (workstream C of #226). Every entry below is a name that
# `vulture poc_homography webapp --min-confidence 60` still flags as unused; each
# carries a categorizing inline comment. Entries whose symbol vulture no longer
# flagged (now used in production) or whose symbol was absent have been removed.

# == django-boilerplate ==
# Django framework boilerplate (AppConfig / urls / settings / asgi-wsgi / middleware / model enums — read by Django, never called directly)
CameraAnnotatorConfig  # django-boilerplate (webapp/camera_annotator/apps.py:6)
default_auto_field  # django-boilerplate (webapp/camera_annotator/apps.py:9)
verbose_name  # django-boilerplate (webapp/camera_annotator/apps.py:11)
app_name  # django-boilerplate (webapp/camera_annotator/urls.py:7)
urlpatterns  # django-boilerplate (webapp/camera_annotator/urls.py:9)
CameraDiagnosticConfig  # django-boilerplate (webapp/camera_diagnostic/apps.py:6)
default_auto_field  # django-boilerplate (webapp/camera_diagnostic/apps.py:9)
verbose_name  # django-boilerplate (webapp/camera_diagnostic/apps.py:11)
_.get_overall_status  # django-boilerplate (webapp/camera_diagnostic/models.py:119)
GOOD  # django-boilerplate (webapp/camera_diagnostic/models.py:248)
NEEDS_IMPROVEMENT  # django-boilerplate (webapp/camera_diagnostic/models.py:249)
BAD  # django-boilerplate (webapp/camera_diagnostic/models.py:250)
app_name  # django-boilerplate (webapp/camera_diagnostic/urls.py:7)
urlpatterns  # django-boilerplate (webapp/camera_diagnostic/urls.py:9)
CameraEvaluationConfig  # django-boilerplate (webapp/camera_evaluation/apps.py:6)
default_auto_field  # django-boilerplate (webapp/camera_evaluation/apps.py:9)
verbose_name  # django-boilerplate (webapp/camera_evaluation/apps.py:11)
app_name  # django-boilerplate (webapp/camera_evaluation/urls.py:11)
urlpatterns  # django-boilerplate (webapp/camera_evaluation/urls.py:13)
CameraLineAnnotatorConfig  # django-boilerplate (webapp/camera_line_annotator/apps.py:6)
default_auto_field  # django-boilerplate (webapp/camera_line_annotator/apps.py:9)
app_name  # django-boilerplate (webapp/camera_line_annotator/urls.py:7)
urlpatterns  # django-boilerplate (webapp/camera_line_annotator/urls.py:9)
CameraSurveyConfig  # django-boilerplate (webapp/camera_survey/apps.py:6)
default_auto_field  # django-boilerplate (webapp/camera_survey/apps.py:9)
verbose_name  # django-boilerplate (webapp/camera_survey/apps.py:11)
app_name  # django-boilerplate (webapp/camera_survey/urls.py:7)
urlpatterns  # django-boilerplate (webapp/camera_survey/urls.py:9)
app_name  # django-boilerplate (webapp/distortion_validator/urls.py:7)
urlpatterns  # django-boilerplate (webapp/distortion_validator/urls.py:9)
GcpConfig  # django-boilerplate (webapp/gcp/apps.py:4)
default_auto_field  # django-boilerplate (webapp/gcp/apps.py:5)
VALID_LAYERS  # django-boilerplate (webapp/gcp/templatetags/satellite_layers.py:29)
satellite_layers_js  # django-boilerplate (webapp/gcp/templatetags/satellite_layers.py:41)
app_name  # django-boilerplate (webapp/gcp/urls.py:11)
urlpatterns  # django-boilerplate (webapp/gcp/urls.py:29)
default_app_config  # django-boilerplate (webapp/homography_precision/__init__.py:3)
HomographyPrecisionConfig  # django-boilerplate (webapp/homography_precision/apps.py:6)
default_auto_field  # django-boilerplate (webapp/homography_precision/apps.py:9)
verbose_name  # django-boilerplate (webapp/homography_precision/apps.py:11)
app_name  # django-boilerplate (webapp/homography_precision/urls.py:11)
urlpatterns  # django-boilerplate (webapp/homography_precision/urls.py:46)
application  # django-boilerplate (webapp/homography_web/asgi.py:16)
SECRET_KEY  # django-boilerplate (webapp/homography_web/settings.py:26)
ALLOWED_HOSTS  # django-boilerplate (webapp/homography_web/settings.py:31)
INSTALLED_APPS  # django-boilerplate (webapp/homography_web/settings.py:36)
MIDDLEWARE  # django-boilerplate (webapp/homography_web/settings.py:56)
ROOT_URLCONF  # django-boilerplate (webapp/homography_web/settings.py:67)
TEMPLATES  # django-boilerplate (webapp/homography_web/settings.py:69)
WSGI_APPLICATION  # django-boilerplate (webapp/homography_web/settings.py:84)
DATABASES  # django-boilerplate (webapp/homography_web/settings.py:90)
AUTH_PASSWORD_VALIDATORS  # django-boilerplate (webapp/homography_web/settings.py:101)
LANGUAGE_CODE  # django-boilerplate (webapp/homography_web/settings.py:120)
TIME_ZONE  # django-boilerplate (webapp/homography_web/settings.py:122)
USE_I18N  # django-boilerplate (webapp/homography_web/settings.py:124)
USE_TZ  # django-boilerplate (webapp/homography_web/settings.py:126)
STATIC_URL  # django-boilerplate (webapp/homography_web/settings.py:132)
STATICFILES_DIRS  # django-boilerplate (webapp/homography_web/settings.py:133)
DEFAULT_AUTO_FIELD  # django-boilerplate (webapp/homography_web/settings.py:140)
urlpatterns  # django-boilerplate (webapp/homography_web/urls.py:21)
application  # django-boilerplate (webapp/homography_web/wsgi.py:16)
LensCalibrationConfig  # django-boilerplate (webapp/lens_calibration/apps.py:6)
default_auto_field  # django-boilerplate (webapp/lens_calibration/apps.py:9)
verbose_name  # django-boilerplate (webapp/lens_calibration/apps.py:11)
app_name  # django-boilerplate (webapp/lens_calibration/urls.py:7)
urlpatterns  # django-boilerplate (webapp/lens_calibration/urls.py:9)
LinePickerConfig  # django-boilerplate (webapp/line_picker/apps.py:6)
default_auto_field  # django-boilerplate (webapp/line_picker/apps.py:9)
verbose_name  # django-boilerplate (webapp/line_picker/apps.py:11)
app_name  # django-boilerplate (webapp/line_picker/urls.py:7)
urlpatterns  # django-boilerplate (webapp/line_picker/urls.py:9)
default_app_config  # django-boilerplate (webapp/point_picker/__init__.py:3)
PointPickerConfig  # django-boilerplate (webapp/point_picker/apps.py:6)
default_auto_field  # django-boilerplate (webapp/point_picker/apps.py:9)
verbose_name  # django-boilerplate (webapp/point_picker/apps.py:11)
app_name  # django-boilerplate (webapp/point_picker/urls.py:7)
urlpatterns  # django-boilerplate (webapp/point_picker/urls.py:9)
DATA_DIR  # django-boilerplate (webapp/homography_web/settings.py:19)
TenantIdMiddleware  # django-boilerplate (webapp/homography_web/middleware.py:10)
_.process_exception  # django-boilerplate (webapp/homography_web/middleware.py:19)

# == orm-mapping ==
# SQLAlchemy ORM mapping attributes (relationships & columns — populated by SA, not referenced in Python)
_.map  # orm-mapping (poc_homography/infrastructure/models/camera_config.py:47)
_.camera_calibration  # orm-mapping (poc_homography/infrastructure/models/camera_config.py:48)
_.lens_calibration_table  # orm-mapping (poc_homography/infrastructure/models/camera_config.py:51)
_.map  # orm-mapping (poc_homography/infrastructure/models/captured_frame.py:47)
_.map  # orm-mapping (poc_homography/infrastructure/models/ground_control_point.py:43)
_.map  # orm-mapping (poc_homography/infrastructure/models/line.py:45)
_.camera_configs  # orm-mapping (poc_homography/infrastructure/models/map.py:46)
_.captured_frames  # orm-mapping (poc_homography/infrastructure/models/map.py:49)
_.ground_control_points  # orm-mapping (poc_homography/infrastructure/models/map.py:53)
_.camera_configs  # orm-mapping (poc_homography/infrastructure/models/tenant.py:34)
_.users  # orm-mapping (poc_homography/infrastructure/models/tenant.py:37)
_.hashed_password  # orm-mapping (poc_homography/infrastructure/models/user.py:28)
_.is_active  # orm-mapping (poc_homography/infrastructure/models/user.py:32)
_.updated_at  # orm-mapping (poc_homography/infrastructure/models/user.py:36)

# == protocol-compliance ==
# Protocol / ABC / interface compliance (abstract members, interface impls, numpy writeable flags)
_.writeable  # protocol-compliance (poc_homography/camera_parameters.py:162)
_.writeable  # protocol-compliance (poc_homography/camera_parameters.py:173)
_.writeable  # protocol-compliance (poc_homography/camera_parameters.py:191)
_.writeable  # protocol-compliance (poc_homography/camera_parameters.py:338)
_.writeable  # protocol-compliance (poc_homography/camera_parameters.py:349)
_.last_ptz_state  # protocol-compliance (poc_homography/domain/protocols/camera_controller.py:24)
_.move_relative  # protocol-compliance (poc_homography/domain/protocols/camera_controller.py:67)
_.writeable  # protocol-compliance (poc_homography/domain/vo/matrix3x3.py:106)
_.writeable  # protocol-compliance (poc_homography/domain/vo/vector3.py:85)
FEATURE_MATCH  # protocol-compliance (poc_homography/homography/interface.py:37)
LEARNED  # protocol-compliance (poc_homography/homography/interface.py:38)
_.identity  # protocol-compliance (poc_homography/homography/interface.py:89)
_.project_point  # protocol-compliance (poc_homography/homography/interface.py:205)
_.project_points  # protocol-compliance (poc_homography/homography/interface.py:218)
image_points  # protocol-compliance (poc_homography/homography/interface.py:220)
point_id_prefix  # protocol-compliance (poc_homography/homography/interface.py:220)
_.get_confidence  # protocol-compliance (poc_homography/homography/interface.py:233)
_.project_point  # protocol-compliance (poc_homography/homography/intrinsic_extrinsic.py:535)
_.project_points  # protocol-compliance (poc_homography/homography/intrinsic_extrinsic.py:558)
_.get_confidence  # protocol-compliance (poc_homography/homography/intrinsic_extrinsic.py:571)
_.writeable  # protocol-compliance (poc_homography/homography/parameters.py:175)
_.writeable  # protocol-compliance (poc_homography/homography/parameters.py:186)
_.writeable  # protocol-compliance (poc_homography/homography/parameters.py:460)
_.writeable  # protocol-compliance (poc_homography/homography/parameters.py:471)
_.writeable  # protocol-compliance (poc_homography/homography/parameters.py:482)
_.last_ptz_state  # protocol-compliance (poc_homography/domain/protocols/camera_device.py:86)
_.move_relative  # protocol-compliance (poc_homography/domain/protocols/camera_device.py:153)
_.inverse  # protocol-compliance (poc_homography/domain/vo/matrix3x3.py:128)
_.transform  # protocol-compliance (poc_homography/homography/interface.py:134)
_.save_plan_config  # protocol-compliance (poc_homography/domain/protocols/survey_run_repository.py:27)
_.load_plan_config  # protocol-compliance (poc_homography/domain/protocols/survey_run_repository.py:31)
_.save_pose_catalog  # protocol-compliance (poc_homography/domain/protocols/survey_run_repository.py:43)
_.get_runs_by_camera_and_pose  # protocol-compliance (poc_homography/domain/protocols/survey_run_repository.py:55)

# == adapter-api ==
# Hikvision ISAPI adapter public surface (CameraDevice protocol + adapter; consumed by tests / api routers / discover CLI outside vulture scan)
image_capabilities  # adapter-api (poc_homography/infrastructure/clients/hikvision/isapi_endpoints.py:113)
_.auth  # adapter-api (poc_homography/infrastructure/clients/hikvision/isapi_transport.py:136)
_.from_config  # adapter-api (poc_homography/infrastructure/clients/hikvision/isapi_client.py:119)
_.goto_preset  # adapter-api (poc_homography/domain/protocols/camera_device.py:200)
_.position3d  # adapter-api (poc_homography/domain/protocols/camera_device.py:211)
_.set_iris  # adapter-api (poc_homography/domain/protocols/camera_device.py:255)
_.set_exposure  # adapter-api (poc_homography/domain/protocols/camera_device.py:266)
_assert_camera_device  # adapter-api (poc_homography/infrastructure/clients/hikvision/isapi_client.py:444)
_.discover_endpoints  # adapter-api (poc_homography/infrastructure/clients/hikvision/isapi_client.py:397)
_.get_ptz_state  # adapter-api (webapp/camera_survey/ptz.py:120)

# == pg-adapter ==
# PostgreSQL _pg adapter functions (called from api/ routers — outside vulture scan paths)
sync_to_ddd_repo_pg  # pg-adapter (poc_homography/calibration/lens_distortion/ddd_sync.py:95)
get_tenants_pg  # pg-adapter (poc_homography/camera_config.py:449)
get_tenant_by_id_pg  # pg-adapter (poc_homography/camera_config.py:461)
get_tenant_by_name_pg  # pg-adapter (poc_homography/camera_config.py:475)
save_to_gcp_repo_pg  # pg-adapter (poc_homography/map_points/gcp_registry.py:279)
list_map_ids_pg  # pg-adapter (poc_homography/map_points/gcp_registry.py:306)
save_line_to_repo_pg  # pg-adapter (webapp/line_picker/state.py:393)
delete_line_from_repo_pg  # pg-adapter (webapp/line_picker/state.py:417)
save_gcp_to_repo_pg  # pg-adapter (webapp/point_picker/state.py:319)
delete_gcp_from_repo_pg  # pg-adapter (webapp/point_picker/state.py:343)

# == repo-api ==
# Repository public / CRUD / query API (consumed across infrastructure layers and tests)
_.clear_cache  # repo-api (poc_homography/infrastructure/repositories/base/repo_yaml.py:98)
_.get_by_camera  # repo-api (poc_homography/infrastructure/repositories/repo_postgres_captured_frame.py:68)
_.clear_cache  # repo-api (poc_homography/infrastructure/repositories/repo_yaml_captured_frame.py:197)
_.get_by_frame_id  # repo-api (poc_homography/infrastructure/repositories/repo_postgres_annotation.py:37)
_.query_frames  # repo-api (poc_homography/infrastructure/repositories/repo_postgres_clean_plate_frame.py:78)

# == cli-command ==
# Typer CLI command callbacks (registered via decorator, never called directly)
projection_command  # cli-command (poc_homography/cli/calibrate.py:21)
comprehensive_command  # cli-command (poc_homography/cli/calibrate.py:75)
YAML  # cli-command (poc_homography/cli/camera.py:38)
distribution_command  # cli-command (poc_homography/cli/gcp.py:18)
intrinsics_command  # cli-command (poc_homography/cli/camera.py:41)
validate_command  # cli-command (poc_homography/cli/camera.py:257)
interactive_command  # cli-command (poc_homography/cli/interactive.py:14)
serve  # cli-command (poc_homography/cli/line_picker.py:17)
serve  # cli-command (poc_homography/cli/point_picker.py:17)
sam3_command  # cli-command (poc_homography/cli/test_cmds.py:14)
run_command  # cli-command (poc_homography/cli/survey.py:19)
status_command  # cli-command (poc_homography/cli/survey.py:62)
abort_command  # cli-command (poc_homography/cli/survey.py:81)
list_command  # cli-command (poc_homography/cli/survey.py:94)
browse_command  # cli-command (poc_homography/cli/survey.py:108)
calibrate_capture_command  # cli-command (poc_homography/cli/calibrate_capture.py:52)
reconstruct_command  # cli-command (poc_homography/cli/cleanplate.py:83)
synth_command  # cli-command (poc_homography/cli/cleanplate.py:169)
upload_command  # cli-command (poc_homography/cli/maps.py:15)
self_calibrate_command  # cli-command (poc_homography/cli/self_calibrate.py:63)

# == domain-api ==
# Domain public API (value-object / entity / algorithm methods exercised by tests or exported as public surface)
_.pixel_to_latlon  # domain-api (poc_homography/domain/vo/geotiff.py:133 — consumed by api/routers/click_to_gps.py)
_.geo_to_pixel  # domain-api (poc_homography/domain/vo/geotiff.py — inverse affine, exercised by tests/test_geotiff_affine_transform.py)
_.detect_from_path  # domain-api (poc_homography/maps/ortho_line_detection.py — offline entry point, exercised by tests/test_ortho_line_detection.py)
_.detect_from_bytes  # domain-api (poc_homography/maps/ortho_line_detection.py — MinIO-bytes entry point, exercised by tests/test_ortho_line_detection.py)
_.remove_entry  # domain-api (poc_homography/calibration/lens_distortion/calibration_table.py:202)
_.get_zoom_levels  # domain-api (poc_homography/calibration/lens_distortion/calibration_table.py:373)
merge_distance_threshold  # domain-api (poc_homography/calibration/lens_distortion/line_detection.py:61)
_.length_pixels  # domain-api (poc_homography/calibration/lens_distortion/models.py:76)
_.angle_degrees  # domain-api (poc_homography/calibration/lens_distortion/models.py:83)
_.length_meters  # domain-api (poc_homography/calibration/lens_distortion/models.py:213)
ground_truth_line  # domain-api (poc_homography/calibration/lens_distortion/models.py:266)
_.to_world_coordinates  # domain-api (poc_homography/calibration/lens_distortion/models.py:288)
error_pixels  # domain-api (poc_homography/calibration/projection.py:34)
best_joint_pan_offset  # domain-api (poc_homography/calibration/projection.py:43)
_.normalized  # domain-api (poc_homography/domain/vo/vector3.py:103)
_.get_approach_config  # domain-api (poc_homography/homography/config.py:270)
_.compute_from_config  # domain-api (poc_homography/homography/intrinsic_extrinsic.py:413)
_.project_point_static  # domain-api (poc_homography/homography/intrinsic_extrinsic.py:653)
inverse_matrix  # domain-api (poc_homography/homography/map_points.py:50)
inverse_matrix  # domain-api (poc_homography/homography/map_points.py:75)
iteration  # domain-api (poc_homography/homography/map_points.py:413)
_.camera_to_map_batch  # domain-api (poc_homography/homography/map_points.py:701)
_.map_to_camera_batch  # domain-api (poc_homography/homography/map_points.py:737)
_.get_result  # domain-api (poc_homography/homography/map_points.py:760)
_.get_homography_matrix  # domain-api (poc_homography/homography/map_points.py:764)
_.get_inverse_matrix  # domain-api (poc_homography/homography/map_points.py:768)
_.from_reference_dict  # domain-api (poc_homography/homography/parameters.py:273)
_.map_dimensions  # domain-api (poc_homography/homography/parameters.py:485)
homography_source  # domain-api (webapp/homography_precision/views.py:905)
line_result  # domain-api (webapp/homography_precision/views.py:923)
get_annotation_repo  # domain-api (webapp/homography_web/frame_utils.py:261)
save_to_line_repo  # domain-api (webapp/line_picker/state.py:329)
list_line_map_ids  # domain-api (webapp/line_picker/state.py:362)
_.get_entry  # domain-api (poc_homography/calibration/lens_distortion/calibration_table.py:377)
_.area  # domain-api (poc_homography/domain/vo/image_dimensions.py:46)
_.inverse  # domain-api (poc_homography/homography/interface.py:98)
_.to_orientation  # domain-api (poc_homography/domain/vo/ptz_state.py:32)
save_to_gcp_repo  # domain-api (poc_homography/map_points/gcp_registry.py:205)
skipped_zooms  # domain-api (poc_homography/calibration/lens_distortion/scene_self_calibration.py:91 — SceneCalibrationResult field consumed by tests/callers, #350)

# == survey-surface ==
# Survey dataset & planner surface (#258/#260/#276) — consumed by sibling capture/phase issues and tests
_.frame_by_index  # survey-surface (poc_homography/domain/entities/survey/video_burst_record.py:83)
_.get_frames_by_phase  # survey-surface (poc_homography/infrastructure/repositories/repo_yaml_survey_run.py:78)
_.get_frames_by_camera  # survey-surface (poc_homography/infrastructure/repositories/repo_yaml_survey_run.py:82)
_.get_frames_by_zoom_range  # survey-surface (poc_homography/infrastructure/repositories/repo_yaml_survey_run.py:86)
_.get_frames_by_burst  # survey-surface (poc_homography/infrastructure/repositories/repo_yaml_survey_run.py:90)
PAUSED  # survey-surface (poc_homography/domain/enums/survey_run_status.py:26)
_.remaining_poses  # survey-surface (poc_homography/survey/planner/run.py:101)
_.advance  # survey-surface (poc_homography/survey/planner/run.py:122)
_.with_status  # survey-surface (poc_homography/survey/planner/run.py:132)
_.header  # survey-surface (poc_homography/survey/planner/run.py:136)
YamlPhaseSink  # survey-surface (poc_homography/infrastructure/survey/yaml_phase_sink.py:30)
_.detail  # survey-surface (poc_homography/horizon/validation.py:34)
calibrate_horizon_envelope  # survey-surface (poc_homography/survey/calibration.py:49)
_.with_pose  # survey-surface (poc_homography/domain/entities/survey/pose_catalog.py:70)
_.from_poses  # survey-surface (poc_homography/domain/entities/survey/pose_catalog.py:82)
_.from_plan_config  # survey-surface (poc_homography/survey/phases/runner.py:143)

# == cleanplate-surface ==
# Clean-plate reconstruction / gallery / MinIO surface (#276/#277/#283/#284/#285) — consumed by downstream loaders, CLI, gallery API and tests
_.world_to_cell  # cleanplate-surface (poc_homography/cleanplate/raster.py:129)
_.cell_to_world  # cleanplate-surface (poc_homography/cleanplate/raster.py:150)
time_bucket  # cleanplate-surface (poc_homography/cleanplate/reconstruct.py:64)
_.presign_get  # cleanplate-surface (poc_homography/infrastructure/clients/minio_frame_store.py:129)
_.get_map  # cleanplate-surface — MinioMapStore GeoTIFF download, consumed by the map tile/info API #292 (poc_homography/infrastructure/clients/minio_map_store.py:136)

# == extrinsic-validation-surface ==
# Hold-out validation + multi-frame consolidation emitted-record fields (#359) — read by tests, CLI and downstream registration consumers, not within poc_homography
_.p90_m  # extrinsic-validation-surface (poc_homography/calibration/extrinsic/validation.py:82)
_.max_m  # extrinsic-validation-surface (poc_homography/calibration/extrinsic/validation.py:83)
_.n_points  # extrinsic-validation-surface (poc_homography/calibration/extrinsic/validation.py:84)
_.num_frames  # extrinsic-validation-surface (poc_homography/calibration/extrinsic/validation.py:132)
_.from_result  # extrinsic-validation-surface (poc_homography/domain/entities/ptz_registration.py:182 — PtzRegistration persistence factory, called by registration writers/tests outside vulture scan, #364)

# == uncertain-needs-follow-up ==
# UNCERTAIN — symbol exists but no callers and no test references found; kept to keep vulture green pending a dead-code follow-up (see #226)
_.get_nearest_entry  # uncertain-needs-follow-up (poc_homography/calibration/lens_distortion/calibration_table.py:393)
_.to_points_array  # uncertain-needs-follow-up (poc_homography/calibration/lens_distortion/models.py:90)
_.to_points_array  # uncertain-needs-follow-up (poc_homography/calibration/lens_distortion/models.py:220)
_.project_image_to_world  # uncertain-needs-follow-up (poc_homography/camera_geometry.py:564)
_.project_world_to_image  # uncertain-needs-follow-up (poc_homography/camera_geometry.py:595)
_.world_to_map  # uncertain-needs-follow-up (poc_homography/camera_geometry.py:623)
_.undistort_point  # uncertain-needs-follow-up (poc_homography/camera_geometry.py:652)
_.from_matrix  # uncertain-needs-follow-up (poc_homography/domain/vo/rotation.py:73)
_.to_matrix  # uncertain-needs-follow-up (poc_homography/domain/vo/rotation.py:88)
_.save_to_yaml  # uncertain-needs-follow-up (poc_homography/homography/config.py:290)
MAP_BASED_ORIGIN  # uncertain-needs-follow-up (poc_homography/homography/interface.py:45)
EDGE_FACTOR_CENTER  # uncertain-needs-follow-up (poc_homography/homography/intrinsic_extrinsic.py:119)
EDGE_FACTOR_EDGE  # uncertain-needs-follow-up (poc_homography/homography/intrinsic_extrinsic.py:120)
EDGE_FACTOR_CORNER_DECAY  # uncertain-needs-follow-up (poc_homography/homography/intrinsic_extrinsic.py:121)
EDGE_FACTOR_MIN  # uncertain-needs-follow-up (poc_homography/homography/intrinsic_extrinsic.py:122)
_.project_image_to_map  # uncertain-needs-follow-up (poc_homography/homography/intrinsic_extrinsic.py:686)
_.result_to_homography_result  # uncertain-needs-follow-up (poc_homography/homography/intrinsic_extrinsic.py:736)
_.load_lens_distortion_calibration  # uncertain-needs-follow-up (poc_homography/homography/intrinsic_extrinsic.py:745)
_.merge_calibration_tables  # uncertain-needs-follow-up (poc_homography/homography/intrinsic_extrinsic.py:771)
_._point_counter  # uncertain-needs-follow-up (poc_homography/homography/map_points.py:125)
_.to_reference_dict  # uncertain-needs-follow-up (poc_homography/homography/parameters.py:338)
_.center_x  # uncertain-needs-follow-up (poc_homography/domain/vo/image_dimensions.py:51)
_.center_y  # uncertain-needs-follow-up (poc_homography/domain/vo/image_dimensions.py:56)
_.has_distortion  # uncertain-needs-follow-up (poc_homography/domain/vo/lens_distortion.py:40)
