"""add clean_plate_frames table

Revision ID: 121dcd273bee
Revises: b7e1c2a9d4f0
Create Date: 2026-06-09 02:42:28.566040

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "121dcd273bee"
down_revision: str | Sequence[str] | None = "b7e1c2a9d4f0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clean_plate_frames",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("camera_id", sa.String(), nullable=False),
        sa.Column("phase", sa.String(), nullable=False),
        sa.Column("pose_id", sa.String(), nullable=False),
        sa.Column("commanded_pan", sa.Float(), nullable=False),
        sa.Column("commanded_tilt", sa.Float(), nullable=False),
        sa.Column("commanded_zoom", sa.Float(), nullable=False),
        sa.Column("burst_id", sa.String(), nullable=True),
        sa.Column("frame_index", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("minio_bucket", sa.String(), nullable=False),
        sa.Column("minio_object_key", sa.String(), nullable=False),
        sa.Column("checksum_sha256", sa.String(), nullable=True),
        sa.Column("record", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clean_plate_frames_burst_id"), "clean_plate_frames", ["burst_id"], unique=False
    )
    op.create_index(
        "ix_clean_plate_frames_camera_captured",
        "clean_plate_frames",
        ["camera_id", "captured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clean_plate_frames_camera_id"), "clean_plate_frames", ["camera_id"], unique=False
    )
    op.create_index(
        op.f("ix_clean_plate_frames_captured_at"),
        "clean_plate_frames",
        ["captured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clean_plate_frames_phase"), "clean_plate_frames", ["phase"], unique=False
    )
    op.create_index(
        op.f("ix_clean_plate_frames_pose_id"), "clean_plate_frames", ["pose_id"], unique=False
    )
    op.create_index(
        op.f("ix_clean_plate_frames_run_id"), "clean_plate_frames", ["run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clean_plate_frames_run_id"), table_name="clean_plate_frames")
    op.drop_index(op.f("ix_clean_plate_frames_pose_id"), table_name="clean_plate_frames")
    op.drop_index(op.f("ix_clean_plate_frames_phase"), table_name="clean_plate_frames")
    op.drop_index(op.f("ix_clean_plate_frames_captured_at"), table_name="clean_plate_frames")
    op.drop_index(op.f("ix_clean_plate_frames_camera_id"), table_name="clean_plate_frames")
    op.drop_index("ix_clean_plate_frames_camera_captured", table_name="clean_plate_frames")
    op.drop_index(op.f("ix_clean_plate_frames_burst_id"), table_name="clean_plate_frames")
    op.drop_table("clean_plate_frames")
    # ### end Alembic commands ###
