"""
Django settings for homography_web project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Data directory at repository root
DATA_DIR = BASE_DIR.parent / "data"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-33xd23v-g5kb1@!t-y3%10m8rx#_7&7jkoqey%=*vo&99l6gv)"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "testserver"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "gcp",
    "point_picker",
    "homography_precision",
    "line_picker",
    "camera_annotator",
    "camera_line_annotator",
    "camera_diagnostic",
    "camera_survey",
    "camera_evaluation",
    "lens_calibration",
    "distortion_validator",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "homography_web.middleware.TenantIdMiddleware",
]

ROOT_URLCONF = "homography_web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "homography_web.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Database users (principle of least privilege):
#   - hom_migrate: DDL + DML (for migrations, CI only)
#   - hom_app: DML on all tables, camera_configs is read-only (runtime)
#   - hom_infra: Only camera_configs table (for infra project)
#
# Non-sensitive config is hardcoded below. Only password comes from env.

# Neon PostgreSQL connection config (non-sensitive, committed to source)
NEON_DB_HOST = "ep-broad-rice-ag826foj-pooler.c-2.eu-central-1.aws.neon.tech"
NEON_DB_NAME = "hom"
NEON_DB_PORT = 5432

# Check for database password (sensitive, from environment)
DB_PASSWORD = os.getenv("DATABASE_PASSWORD")

# For migrations, use hom_migrate user (set DATABASE_USER=hom_migrate in CI)
DB_USER = os.getenv("DATABASE_USER", "hom_app")

if DB_PASSWORD:
    # PostgreSQL with Neon (production/CI)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": NEON_DB_NAME,
            "USER": DB_USER,
            "PASSWORD": DB_PASSWORD,
            "HOST": NEON_DB_HOST,
            "PORT": NEON_DB_PORT,
            "OPTIONS": {
                "sslmode": "require",
            },
        }
    }
else:
    # Fallback to SQLite for local development (no DATABASE_PASSWORD set)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Camera Diagnostic App Settings
CAMERA_DIAGNOSTIC_SCREENSHOTS_DIR = BASE_DIR / "diagnostic_screenshots"
# Browser headless mode for WebUI tests (False for Hikvision compatibility, True for server deployment)
CAMERA_DIAGNOSTIC_BROWSER_HEADLESS = False
