#!/usr/bin/env bash
set -euo pipefail

# Generate .env file from Bitwarden Secrets Manager
# Usage: BWS_ACCESS_TOKEN=<token> ./scripts/generate-env.sh

# Bitwarden Secrets Manager project: "GoClever"
BWS_PROJECT_ID="19f59ce7-1fec-4885-b86b-b3b701408989"

: "${BWS_ACCESS_TOKEN:?BWS_ACCESS_TOKEN not set}"

# Get script directory and project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "Fetching secrets from Bitwarden Secrets Manager..."

# Run bws with secrets injected as env vars
bws run --project-id "$BWS_PROJECT_ID" -- bash -c "cat > \"$PROJECT_ROOT/.env\" <<EOF
# Generated by scripts/generate-env.sh from Bitwarden Secrets Manager
# Project: GoClever
# Do not commit this file!

# Database configuration (hom_app user for runtime)
DATABASE_PASSWORD=\$HOM_DB_PASSWORD_APP
DATABASE_USER=hom_app

# Camera credentials
CAMERA_USERNAME=admin
CAMERA_PASSWORD=\$CAMERA_PASSWORD
EOF
"

echo ".env created at $PROJECT_ROOT/.env from Bitwarden secrets"
